#!/bin/bash
export OCP4_AWS_WORKSPACE="${OCP4_AWS_WORKSPACE:-$(readlink -f .)}"

OI_LOCAL_VERSION="$(openshift-install version | grep quay.io | sed -e 's,.*\(sha256:.*\),\1,')"
OI_LATEST_VERSION="$(curl -s -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/release.txt | grep "Digest: " | sed -e 's,.*\(sha256:.*\),\1,')"

if [ "$OI_LOCAL_VERSION" != "$OI_LATEST_VERSION" ]; then
    echo "WARNING: Your local version of openshift-install tool is different from the latest one."
    echo "         Please update your local version to make sure the OCP4 cluster creating/destroying works properly."
    echo "         The latest version can be found here: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/"
fi